_VOWELS = "aieou"
_EXCEPTION = {
    "abacus": "abaci",
    "actus": "acti",
    "addendum": "addenda",
    "adieu": "adieux",
    "agape": "agapae",
    "agendum": "agenda",
    "agora": "agorae",
    "aircraft": "aircraft",
    "airman": "airmen",
    "ala": "alae",
    "alderman": "aldermen",
    "alumna": "alumnae",
    "amenorrhoea": "amenorrhoeae",
    "amicus": "amici",
    "amoeba": "amoebae",
    "amphora": "amphorae",
    "angelfish": "angelfish",
    "antelope": "antelope",
    "antenna": "antennae",
    "aquarium": "aquaria",
    "atrium": "atria",
    "aura": "aurae",
    "aureus": "aurei",
    "bacillus": "bacilli",
    "bacterium": "bacteria",
    "barman": "barmen",
    "barracuda": "barracuda",
    "batsman": "batsmen",
    "beau": "beaux",
    "beef": "beefs",
    "bellman": "bellmen",
    "bi": "bi",
    "bison": "bison",
    "bitumen": "bitumina",
    "boardman": "boardmen",
    "boatman": "boatmen",
    "bogeyman": "bogeymen",
    "bolus": "boli",
    "bonito": "bonito",
    "bonsai": "bonsai",
    "bookman": "bookmen",
    "bordeaux": "bordeaux",
    "bowman": "bowmen",
    "brainchild": "brainchildren",
    "bream": "bream",
    "brit": "brit",
    "buffalo": "buffalo",
    "bursa": "bursae",
    "bus": "buses",
    "businessman": "businessmen",
    "businesswoman": "businesswomen",
    "cactus": "cacti",
    "caecum": "caeca",
    "calculus": "calculi",
    "cameraman": "cameramen",
    "cannon": "cannon",
    "cantharus": "canthari",
    "carman": "carmen",
    "carp": "carp",
    "catfish": "catfish",
    "cattle": "cattle",
    "caveman": "cavemen",
    "cella": "cellae",
    "centrale": "centralia",
    "chad": "chad",
    "chairman": "chaimen",
    "chairwoman": "chairwomen",
    "chapman": "chapmen",
    "chateau": "chateaux",
    "chef": "chefs",
    "chela": "chelae",
    "chief": "chiefs",
    "child": "children",
    "chinaman": "chinamen",
    "chon": "chon",
    "chou": "choux",
    "churchman": "churchmen",
    "cirrus": "cirri",
    "clergyman": "clergymen",
    "clownfish": "clownfish",
    "clubman": "clubmen",
    "coachman": "coachmen",
    "coalman": "coalmen",
    "collegium": "collegia",
    "coloratura": "coloratura",
    "congressman": "congressmen",
    "conman": "conmen",
    "consortium": "consortia",
    "corpus": "corpora",
    "countryman": "countrymen",
    "craft": "craft",
    "craftsman": "craftsmen",
    "crewman": "crewmen",
    "criterion": "criteria",
    "crus": "crura",
    "cryptosporidium": "cryptosporidia",
    "cumulus": "cumuli",
    "curriculum": "curricula",
    "daimyo": "daimyo",
    "dairyman": "dairymen",
    "dalesman": "dalesmen",
    "datum": "data",
    "deceased": "deceased",
    "deci": "decies",
    "deer": "deer",
    "deni": "deni",
    "dice": "dice",
    "dictum": "dicta",
    "die": "dice",
    "dilettante": "dilettanti",
    "disequilibrium": "disequilibria",
    "diva": "dive",
    "dogfish": "dogfish",
    "doorman": "doormen",
    "dormouse": "dormice",
    "draftsman": "draftsmen",
    "draughtsman": "draughtsmen",
    "duodenum": "duodena",
    "dustman": "dustmen",
    "dutchman": "dutchmen",
    "ealdorman": "ealdormen",
    "eczema": "eczemata",
    "elk": "elk",
    "endothelium": "endothelia",
    "eq": "eqq",
    "ethos": "ethe",
    "eucalyptus": "eucalypti",
    "everyman": "everymen",
    "fabliau": "fabliaux",
    "factum": "facta",
    "fair": "fair",
    "fauna": "faunae",
    "ferryman": "ferrymen",
    "fig": "fig",
    "fireman": "firemen",
    "firstborn": "firstborn",
    "fisherman": "fishermen",
    "fish": "fish",
    "flashman": "flashmen",
    "flatfish": "flatfish",
    "focus": "foci",
    "folk": "folk",
    "foote": "feete",
    "foot": "feet",
    "footman": "footmen",
    "foramen": "foramina",
    "forefoot": "forefeet",
    "foreman": "foremen",
    "formula": "formulae",
    "fowl": "fowl",
    "freedman": "freedmen",
    "freeman": "freemen",
    "freshman": "freshmen",
    "frontman": "frontmen",
    "fundus": "fundi",
    "fungus": "fungi",
    "gaijin": "gaijin",
    "gal": "gal",
    "garda": "gardai",
    "gas": "gases",
    "gemma": "gemmae",
    "genie": "genii",
    "gentleman": "gentlemen",
    "gentlewoman": "gentlewomen",
    "genus": "genera",
    "gnome": "gnomai",
    "goby": "goby",
    "godman": "godmen",
    "goldfish": "goldfish",
    "gonococcus": "gonococci",
    "goodman": "goodmen",
    "goose": "geese",
    "grandchild": "grandchildren",
    "grand": "grand",
    "grayling": "grayling",
    "grice": "grice",
    "grosz": "groszy",
    "groundsman": "groundsmen",
    "grouse": "grouse",
    "gt": "gtt",
    "guardsman": "guardsmen",
    "gulf": "gulfs",
    "gunman": "gunmen",
    "gymnasium": "gymnasia",
    "hackman": "hackmen",
    "haddock": "haddock",
    "haiku": "haiku",
    "handyman": "handymen",
    "hangman": "hangmen",
    "hardman": "hardmen",
    "headman": "headmen",
    "heathen": "heathen",
    "helmsman": "helmsmen",
    "henchman": "henchmen",
    "herdsman": "herdsmen",
    "hertz": "hertz",
    "highwayman": "highwaymen",
    "hillman": "hillmen",
    "hippocampus": "hippocampi",
    "hitman": "hitmen",
    "hoof": "hoofs",
    "horseman": "horsemen",
    "horsewoman": "horsewomen",
    "houseman": "housemen",
    "humerus": "humeri",
    "hundredweight": "hundredweight",
    "huntsman": "huntsmen",
    "husbandman": "husbandmen",
    "hypothalamus": "hypothalami",
    "ice": "ice",
    "ileum": "ilea",
    "imperium": "imperia",
    "incubus": "incubi",
    "infantryman": "infantrymen",
    "information": "information",
    "injuria": "injurie",
    "jackman": "jackmen",
    "jejunum": "jejuna",
    "jellyfish": "jellyfish",
    "journeyman": "journeymen",
    "juba": "jubae",
    "jun": "jun",
    "kama": "kama",
    "kanji": "kanji",
    "karateka": "karateka",
    "kibbutz": "kibbutzim",
    "kin": "kin",
    "kinsman": "kinsmen",
    "kinswoman": "kinswomen",
    "kirkman": "kirkmen",
    "koi": "koi",
    "ko": "ko",
    "kouros": "kouroi",
    "krill": "krill",
    "krona": "kronor",
    "krone": "kroner",
    "lacuna": "lacunae",
    "layman": "laymen",
    "letterman": "lettermen",
    "lev": "leva",
    "lexicon": "lexica",
    "libra": "librae",
    "lightman": "lightmen",
    "linea": "lineae",
    "linesman": "linesmen",
    "lingua": "linguae",
    "lionfish": "lionfish",
    "locus": "loci",
    "logos": "logoi",
    "loof": "loofs",
    "louse": "lice",
    "lungfish": "lungfish",
    "lux": "lux",
    "lymphoma": "lymphomata",
    "machinery": "machinery",
    "mackerel": "mackerel",
    "madman": "madmen",
    "mage": "magi",
    "mala": "malae",
    "mamma": "mammae",
    "manga": "manga",
    "man": "men",
    "marksman": "marksmen",
    "marlin": "marlin",
    "masterman": "mastermen",
    "matza": "matzot",
    "maximum": "maxima",
    "mc": "mc",
    "means": "means",
    "media": "mediae",
    "medium": "media",
    "mensa": "mensae",
    "mg/kg": "mg/kg",
    "middleman": "middlemen",
    "midshipman": "midshipmen",
    "milieu": "milieux",
    "military": "military",
    "milkman": "milkmen",
    "millennium": "millennia",
    "minimum": "minima",
    "mink": "mink",
    "modicum": "modica",
    "modulus": "moduli",
    "modus": "modi",
    "monkfish": "monkfish",
    "moose": "moose",
    "mouse": "mice",
    "mucosa": "mucosae",
    "mycobacterium": "mycobacteria",
    "nebula": "nebulae",
    "newsman": "newsmen",
    "news": "news",
    "nightwatchman": "nightwatchmen",
    "nimbus": "nimbi",
    "ninja": "ninja",
    "nobleman": "noblemen",
    "nova": "novae",
    "nox": "nox",
    "nucleus": "nuclei",
    "oesophagus": "oesophagi",
    "offspring": "offspring",
    "oldman": "oldmen",
    "ombudsman": "ombudsmen",
    "optimum": "optima",
    "os": "ossa",
    "ovum": "ova",
    "ox": "oxen",
    "oz": "oz",
    "paceman": "pacemen",
    "packman": "packmen",
    "palladium": "palladia",
    "pallium": "pallia",
    "paolo": "paoli",
    "papilla": "papillae",
    "papyrus": "papyri",
    "pct": "pct",
    "pease": "peasen",
    "penman": "penmen",
    "penny": "pence",
    "percent": "percent",
    "perihelion": "perihelia",
    "person": "people",
    "pfennig": "pfennige",
    "phallus": "phalli",
    "phenomenon": "phenomena",
    "phlox": "phlox",
    "phoenix": "phoenix",
    "phylum": "phyla",
    "placenta": "placentae",
    "plaice": "plaice",
    "plateau": "plateaux",
    "ploughman": "ploughmen",
    "policeman": "policemen",
    "policewoman": "policewomen",
    "pomfret": "pomfret",
    "porta": "portae",
    "portman": "portmen",
    "postman": "postmen",
    "prawn": "prawn",
    "presidium": "presidia",
    "proof": "proofs",
    "proteus": "protei",
    "ptarmigan": "ptarmigan",
    "pylorus": "pylori",
    "quadra": "quadrae",
    "quail": "quail",
    "quantum": "quanta",
    "radius": "radii",
    "railwayman": "railwaymen",
    "ramus": "rami",
    "rectum": "recta",
    "redman": "redmen",
    "referendum": "referenda",
    "reticulum": "reticula",
    "rhombus": "rhombi",
    "rhubarb": "rhubarb",
    "rifleman": "riflemen",
    "rima": "rimae",
    "rin": "rin",
    "roach": "roach",
    "rostrum": "rostra",
    "roux": "roux",
    "rumen": "rumina",
    "salesman": "salesmen",
    "salmon": "salmon",
    "samurai": "samurai",
    "sandgrouse": "sandgrouse",
    "sarcophagus": "sarcophagi",
    "scampi": "scampi",
    "schema": "schemata",
    "schoolchild": "schoolchildren",
    "seaman": "seamen",
    "sec": "sec",
    "seq": "seqq",
    "series": "series",
    "serviceman": "servicemen",
    "shearman": "shearmen",
    "sheep": "sheep",
    "shellfish": "shellfish",
    "shipman": "shipmen",
    "showman": "showmen",
    "shrimp": "shrimp",
    "signalman": "signalmen",
    "silverfish": "silverfish",
    "snowman": "snowmen",
    "spacecraft": "spacecraft",
    "spaceman": "spacemen",
    "spawn": "spawn",
    "spearman": "spearmen",
    "species": "species",
    "spectrum": "spectra",
    "sperm": "sperm",
    "spey": "spies",
    "spokesman": "spokesmen",
    "spokeswoman": "spokeswomen",
    "sportsman": "sportsmen",
    "sprat": "sprat",
    "springbok": "springbok",
    "sputum": "sputa",
    "stadia": "stadia",
    "staphylococcus": "staphylococci",
    "statesman": "statesmen",
    "steersman": "steersmen",
    "stella": "stellae",
    "sternum": "sterna",
    "stigma": "stigmata",
    "stimulus": "stimuli",
    "stockman": "stockmen",
    "stoma": "stomata",
    "storeman": "storemen",
    "stratum": "strata",
    "stratus": "strati",
    "stroma": "stromata",
    "strongman": "strongmen",
    "stuntman": "stuntmen",
    "sturgeon": "sturgeon",
    "stylus": "styli",
    "substratum": "substrata",
    "sumo": "sumo",
    "superman": "supermen",
    "swine": "swine",
    "swordfish": "swordfish",
    "swordsman": "swordsmen",
    "sylabus": "syllabi",
    "syllabus": "syllabi",
    "tableau": "tableaux",
    "tarsus": "tarsi",
    "taxman": "taxmen",
    "tench": "tench",
    "terminus": "termini",
    "tetanus": "tetani",
    "thalamus": "thalami",
    "thesaurus": "thesauri",
    "thrombus": "thrombi",
    "thymus": "thymi",
    "tooth": "teeth",
    "torus": "tori",
    "townsman": "townsmen",
    "toxoplasma": "toxoplasmata",
    "tradesman": "tradesmen",
    "triforium": "triforia",
    "trivia": "trivia",
    "trout": "trout",
    "tsunami": "tsunami",
    "tuna": "tuna",
    "turbot": "turbot",
    "tyrannosaurus": "tyrannosauri",
    "uterus": "uteri",
    "uva": "uvae",
    "vas": "vasa",
    "vermin": "vermin",
    "vertebra": "vertebræ",
    "vertex": "vertices",
    "vita": "vitae",
    "waltz": "waltzes",
    "warehouseman": "warehousemen",
    "watchman": "watchmen",
    "waterfowl": "waterfowl",
    "waterman": "watermen",
    "weatherman": "weathermen",
    "wildebeest": "wildebeest",
    "wildman": "wildmen",
    "wiseman": "wisemen",
    "woman": "women",
    "woodcock": "woodcock",
    "woodman": "woodmen",
    "workman": "workmen",
    "wpm": "wpm",
    "xu": "xu",
    "yen": "yen",
    "yeoman": "yeomen",
    "yeti": "yeti",
    "yuan": "yuan",
    "yu": "yu",
    "zebra": "zebra",
    "zhu": "zhu",
    "zloty": "zloty",
}

def plural(word, count=2, exception=None):
    if count == 1 or count == -1:
        return word

    if exception is not None:
        return exception

    lword = word.lower()
    last_two = lword[-2:]
    last_one = last_two[1]
    next_to_last = last_two[0]

    if word.isupper():
        s = "S"
        es = "ES"
        ies = "IES"
        ses = "SES"
        ves = "VES"
        zes = "ZES"
    else:
        s = "s"
        es = "es"
        ies = "ies"
        ses = "ses"
        ves = "ves"
        zes = "zes"

    #
    # RULE: Exceptions
    #
    if lword in _EXCEPTION:
        if word.isupper():
            return _EXCEPTION[lword].upper()
        if word[0].isupper():
            return _EXCEPTION[lword].capitalize()
        return _EXCEPTION[lword]

    #
    # RULE: Words that end in Y
    #
    if last_one == "y" \
    and next_to_last in _VOWELS:
        return word + s

    if last_one == "y":
        return word[:-1] + ies

    #
    # RULE: Words that end in CH, SH, SS, X
    #
    if last_two == "ch" \
    or last_two == "sh" \
    or last_two == "ss" \
    or last_one == "x":
        return word + es

    #
    # RULE: Words that end in IS
    #
    if last_two == "is":
        return word[:-2] + es

    #
    # RULE: Words that end in S, Z
    #
    if last_one == "s":
        return word + ses

    if last_one == "z":
        return word + zes

    #
    # RULE: Words that end in "O"
    #
    if last_one == "o" \
    and next_to_last not in _VOWELS:
        return word + es

    if last_one == "o":
        return word + s

    #
    # RULE: Words that end in F, FE, FF
    #
    if last_two == "ff":
        return word + s

    if last_two == "fe":
        return word[:-2] + ves

    if last_one == "f":
        return word[:-1] + ves

    # US->I ?
    # ON->A ?
    # UM->A ?
    # IX->XES ?
    # EX->CES ?

    #
    # RULE: Add an S
    #
    return word + s
